Fix: chmod を実行する位置を変更する
before_script では遅すぎるので before_install に変更する。デフォルトの
コードがあるので [1] を参考にして追加する。

[1]: https://github.com/rocq-community/docker-coq-action/blob/126d4ac196f8133729a1cb0d2aa1ee7106efec58/action.yml#L17-L22

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -12,7 +12,7 @@ jobs:
       with:
         coq_version: '8.20.1'
         ocaml_version: 'default'
-        before_script: |
+        before_install: |
           startGroup "Workaround permission issue"
             echo "=== chmod ==="
             sudo chmod -R a=u ./
@@ -23,4 +23,8 @@ jobs:
             echo "=== Directory Permission ==="
             ls -ld . .git
             echo "=== Git Status Check ==="
+            git status || echo "git status failed"
+          endGroup
+          startGroup "Print opam config"
+            opam config list; opam repo list; opam list
           endGroup
